- name: Find existing VMPools
  ovirt_vmpools_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "datacenter={{ data_center_name }}"

- name: Remove VMPools
  ovirt_vms:
    state: absent
    id: "{{ ovirt_item.id }}"
    auth: "{{ ovirt_auth }}"
  with_items: "{{ ovirt_vm_pools }}"
  loop_control:
    loop_var: ovirt_item
